### ISSUE TITLE
[프로필 메인] 프로필 화면 구현

### ISSUE THREAD

**Issue by mint3382** [Prography-RoomE/roome_ios#40]
## 📚 작업 설명
- 프로필 메인 페이지 중에서 프로필 화면 구현
- category는 아직 mock 상태 

## ✅ TODO
- [x] 프로필 메인 페이지 tabBarController 설정
- [x] 유저 정보 띄우는 View 구현
- [x] 카카오로 공유 구현
- [x] 프로필 카드 구현
- [x] 프로필 정보 띄우는 View 구현
- [x] 선택한 프로필 정보 화면에 띄우기
