### ISSUE TITLE
[프로필 수정] 닉네임, 사진

### ISSUE THREAD

**Issue by mint3382** [Prography-RoomE/roome_ios#43]
## 📚 작업 설명
- 유저 프로필 수정 화면 구현
- 사진 가져오는 로직 구현

## ✅ TODO
- [x] 유저 프로필 수정 화면 구현
- [x] 사진 촬영
- [x] 앨범에서 사진 선택
- [x] 기본 이미지 사용
- [x] 닫기 누를 때 수정사항 있는지 없는지 체크 후 수정 사항 있으면 팝업 띄우기
- [x] 서버에 이미지 보내기
