### ISSUE TITLE
Google Analytics 

### ISSUE THREAD

**Issue by mint3382** [Prography-RoomE/roome_ios#57]
## 📚 작업 설명
- Google Analytics 붙이기

## ✅ TODO
- [x] Google Analytics 계정에 iOS 생성
- [x] Google Analytics 관련 pod 추가
- [x] Google Analytics 필요한 위치에 코드 입력
- [x] Privacy Manifest 대응 확인
