### ISSUE TITLE
[회원가입] 닉네임 화면 구현

### ISSUE THREAD

**Issue by mint3382** [Prography-RoomE/roome_ios#8]
## TODO

- [x] 기본 화면
- [x] 버튼 활성화 데이터 스트림
- [x] 키보드 업 다운 시 버튼 변화
- [x] 닉네임 체크 로직 -> 입력 가능 여부 체크
